"""Recorded demo-safe telemetry artifacts for instant reproducible presentation."""

from __future__ import annotations

from typing import Any

SAFE_DEMO_SCENARIOS: dict[str, dict[str, Any]] = {
    "clean": {
        "title": "Clean Authentic Boot",
        "description": "Standard authentic boot chain with valid ML-DSA-65 signatures and normal baseline workload.",
        "stages": [
            {"id": "S0", "name": "BootROM", "status": "OK", "time_ms": 3.1, "detail": "Verified S1 with ML-DSA-65"},
            {"id": "S1", "name": "Bootloader", "status": "OK", "time_ms": 8.4, "detail": "Parsed Device Tree & Verified S2"},
            {"id": "S2", "name": "Kernel", "status": "OK", "time_ms": 17.2, "detail": "Initialized Task Tables & Verified S3"},
            {"id": "S3", "name": "Init/Services", "status": "OK", "time_ms": 11.8, "detail": "Launched 5 services (svc_a..e)"},
        ],
        "gate1_crypto": {"status": "PASS", "algorithm": "ML-DSA-65", "detail": "All stage signatures authentic"},
        "gate2_measure": {"status": "PASS", "detail": "PCR[0..3] extended and event log replay consistent"},
        "gate3_behavior": {"status": "PASS", "score": 0.08, "detail": "Telemetry within 1.1sigma normal baseline"},
        "pcrs": {
            "PCR0": "7e3b8a1c9f4d2e0b5a6c7d8e9f0a1b2c3d4e5f6a",
            "PCR1": "c9e4b2d1a0f8e7c6b5a4d3c2b1a0f9e8d7c6b5a4",
            "PCR2": "f8a7b6c5d4e3f2a1b0c9d8e7f6a5b4c3d2e1f0a9",
            "PCR3": "3d2e1f0a9b8c7d6e5f4a3b2c1d0e9f8a7b6c5d4e",
        },
        "verdict": "PASS",
        "reason": "All cryptographic signatures valid; behavior consistent with trusted baseline",
        "attestation": "TRUSTED (ML-DSA-65 Signed Quote)",
        "attributions": [
            {"feature": "t_exec_s2", "observed": "10.2 ms", "baseline": "10.0 ms", "sigma": "+0.2sigma"},
            {"feature": "rss_peak_mb", "observed": "16.1 MB", "baseline": "15.8 MB", "sigma": "+0.3sigma"},
            {"feature": "ctx_switch_ratio", "observed": "0.14", "baseline": "0.15", "sigma": "-0.1sigma"},
        ],
    },
    "byte_tamper": {
        "title": "Naive Byte Tamper Attack",
        "description": "Attacker injected arbitrary bytecode into the S1 bootloader binary.",
        "stages": [
            {"id": "S0", "name": "BootROM", "status": "FAIL", "time_ms": 2.8, "detail": "Signature verification failed for S1 payload"},
            {"id": "S1", "name": "Bootloader", "status": "HALTED", "time_ms": 0.0, "detail": "Execution blocked by Gate 1"},
            {"id": "S2", "name": "Kernel", "status": "HALTED", "time_ms": 0.0, "detail": "Execution blocked by Gate 1"},
            {"id": "S3", "name": "Init/Services", "status": "HALTED", "time_ms": 0.0, "detail": "Execution blocked by Gate 1"},
        ],
        "gate1_crypto": {"status": "FAIL", "algorithm": "ML-DSA-65", "detail": "Payload SHA-256 mismatch (Gate 1 FAIL-CLOSED)"},
        "gate2_measure": {"status": "HALTED", "detail": "Boot aborted before PCR extension"},
        "gate3_behavior": {"status": "HALTED", "score": 1.0, "detail": "Not reached (Gate 1 blocked execution)"},
        "pcrs": {
            "PCR0": "7e3b8a1c9f4d2e0b5a6c7d8e9f0a1b2c3d4e5f6a",
            "PCR1": "0000000000000000000000000000000000000000",
            "PCR2": "0000000000000000000000000000000000000000",
            "PCR3": "0000000000000000000000000000000000000000",
        },
        "verdict": "HALT",
        "reason": "Traditional Secure Boot Gate 1: Cryptographic signature mismatch",
        "attestation": "UNTRUSTED (Boot Aborted at S0)",
        "attributions": [
            {"feature": "crypto_verify_s0", "observed": "INVALID", "baseline": "VALID", "sigma": "N/A"},
        ],
    },
    "a1_downgrade": {
        "title": "Attack A1: Signed Version Downgrade",
        "description": "Attacker replaced authentic Kernel v2.0 (SVN=5) with authentic legacy Kernel v1.2 (SVN=3).",
        "stages": [
            {"id": "S0", "name": "BootROM", "status": "OK", "time_ms": 3.1, "detail": "Verified S1 with ML-DSA-65"},
            {"id": "S1", "name": "Bootloader", "status": "OK", "time_ms": 8.2, "detail": "Verified S2 with ML-DSA-65 (Authentic Key)"},
            {"id": "S2", "name": "Kernel", "status": "OK", "time_ms": 16.5, "detail": "Kernel v1.2 legacy image loaded"},
            {"id": "S3", "name": "Init/Services", "status": "OK", "time_ms": 11.4, "detail": "Launched services"},
        ],
        "gate1_crypto": {"status": "PASS", "algorithm": "ML-DSA-65", "detail": "Authentic vendor signature verified"},
        "gate2_measure": {"status": "PASS", "detail": "PCR extended with authentic legacy digest"},
        "gate3_behavior": {"status": "RULE_FAIL", "score": 0.85, "detail": "RULE_SVN_ROLLBACK: observed SVN=3 < trusted SVN=5"},
        "pcrs": {
            "PCR0": "7e3b8a1c9f4d2e0b5a6c7d8e9f0a1b2c3d4e5f6a",
            "PCR1": "d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3",
            "PCR2": "a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0",
            "PCR3": "3d2e1f0a9b8c7d6e5f4a3b2c1d0e9f8a7b6c5d4e",
        },
        "verdict": "HALT",
        "reason": "Deterministic Security Rule Floor: Security Version Counter Rollback detected (SVN=3 < 5)",
        "attestation": "UNTRUSTED (Security Version Rollback)",
        "attributions": [
            {"feature": "security_version_counter", "observed": "3", "baseline": "5", "sigma": "-4.2sigma"},
            {"feature": "t_exec_s2", "observed": "16.5 ms", "baseline": "10.0 ms", "sigma": "+2.1sigma"},
            {"feature": "payload_size", "observed": "1024 B", "baseline": "1536 B", "sigma": "-1.8sigma"},
        ],
    },
    "a2_toctou": {
        "title": "Attack A2: TOCTOU Config Swap",
        "description": "Unmeasured configuration file swapped between verification and execution, inducing heavy compute overhead.",
        "stages": [
            {"id": "S0", "name": "BootROM", "status": "OK", "time_ms": 3.1, "detail": "Verified S1 with ML-DSA-65"},
            {"id": "S1", "name": "Bootloader", "status": "OK", "time_ms": 8.5, "detail": "Verified S2 with ML-DSA-65"},
            {"id": "S2", "name": "Kernel", "status": "WARN", "time_ms": 48.2, "detail": "Anomalous CPU/memory spike during init"},
            {"id": "S3", "name": "Init/Services", "status": "OK", "time_ms": 12.0, "detail": "Launched services"},
        ],
        "gate1_crypto": {"status": "PASS", "algorithm": "ML-DSA-65", "detail": "Signatures valid at verification time"},
        "gate2_measure": {"status": "PASS", "detail": "Initial static measurements verified"},
        "gate3_behavior": {"status": "ANOMALY", "score": 0.89, "detail": "Isolation Forest flagged abnormal resource consumption"},
        "pcrs": {
            "PCR0": "7e3b8a1c9f4d2e0b5a6c7d8e9f0a1b2c3d4e5f6a",
            "PCR1": "c9e4b2d1a0f8e7c6b5a4d3c2b1a0f9e8d7c6b5a4",
            "PCR2": "f8a7b6c5d4e3f2a1b0c9d8e7f6a5b4c3d2e1f0a9",
            "PCR3": "3d2e1f0a9b8c7d6e5f4a3b2c1d0e9f8a7b6c5d4e",
        },
        "verdict": "WARN",
        "reason": "Authentic signatures verified; AI behavioral anomaly detected (Excessive S2 CPU/Memory/IO)",
        "attestation": "REDUCED_TRUST (Behavioral Anomaly Warning)",
        "attributions": [
            {"feature": "t_exec_s2", "observed": "48.2 ms", "baseline": "10.0 ms", "sigma": "+5.8sigma"},
            {"feature": "rss_s2_mb", "observed": "48.5 MB", "baseline": "14.0 MB", "sigma": "+4.9sigma"},
            {"feature": "io_bytes_read_kb", "observed": "80.0 KB", "baseline": "8.0 KB", "sigma": "+4.2sigma"},
        ],
    },
    "a3_reorder": {
        "title": "Attack A3: Signed Service Reorder",
        "description": "Attacker launched legitimate services out of order and inserted unexpected diagnostic service.",
        "stages": [
            {"id": "S0", "name": "BootROM", "status": "OK", "time_ms": 3.1, "detail": "Verified S1 with ML-DSA-65"},
            {"id": "S1", "name": "Bootloader", "status": "OK", "time_ms": 8.4, "detail": "Verified S2 with ML-DSA-65"},
            {"id": "S2", "name": "Kernel", "status": "OK", "time_ms": 17.0, "detail": "Verified S3 with ML-DSA-65"},
            {"id": "S3", "name": "Init/Services", "status": "WARN", "time_ms": 16.5, "detail": "Abnormal sequence [svc_e -> svc_diag -> svc_a]"},
        ],
        "gate1_crypto": {"status": "PASS", "algorithm": "ML-DSA-65", "detail": "All individual service binaries authentic"},
        "gate2_measure": {"status": "PASS", "detail": "Individual measurements allowlisted"},
        "gate3_behavior": {"status": "ANOMALY", "score": 0.95, "detail": "Markov model detected zero-support transition (svc_e -> svc_diag)"},
        "pcrs": {
            "PCR0": "7e3b8a1c9f4d2e0b5a6c7d8e9f0a1b2c3d4e5f6a",
            "PCR1": "c9e4b2d1a0f8e7c6b5a4d3c2b1a0f9e8d7c6b5a4",
            "PCR2": "f8a7b6c5d4e3f2a1b0c9d8e7f6a5b4c3d2e1f0a9",
            "PCR3": "8e7d6c5b4a3f2e1d0c9b8a7f6e5d4c3b2a1f0e9d",
        },
        "verdict": "WARN",
        "reason": "Authentic signatures verified; Markov Sequence anomaly detected (Unseen service ordering)",
        "attestation": "REDUCED_TRUST (Sequence Anomaly Warning)",
        "attributions": [
            {"feature": "markov_transition_nll", "observed": "8.4 NLL", "baseline": "1.2 NLL", "sigma": "+6.2sigma"},
            {"feature": "unseen_transitions", "observed": "2", "baseline": "0", "sigma": "+5.0sigma"},
            {"feature": "t_exec_s3", "observed": "16.5 ms", "baseline": "11.8 ms", "sigma": "+2.4sigma"},
        ],
    },
    "a4_drift": {
        "title": "Attack A4: Slow-Drip Behavioral Drift",
        "description": "Progressive, stealthy +4ms latency accumulated across 20 successive boots; caught by EWMA / CUSUM monitor.",
        "stages": [
            {"id": "S0", "name": "BootROM", "status": "OK", "time_ms": 3.1, "detail": "Verified S1 with ML-DSA-65"},
            {"id": "S1", "name": "Bootloader", "status": "OK", "time_ms": 8.6, "detail": "Verified S2 with ML-DSA-65"},
            {"id": "S2", "name": "Kernel", "status": "WARN", "time_ms": 78.0, "detail": "Accumulated stealth drift across boots"},
            {"id": "S3", "name": "Init/Services", "status": "OK", "time_ms": 12.2, "detail": "Launched services"},
        ],
        "gate1_crypto": {"status": "PASS", "algorithm": "ML-DSA-65", "detail": "Valid PQC signatures on all 20 boots"},
        "gate2_measure": {"status": "PASS", "detail": "PCR extensions verified"},
        "gate3_behavior": {"status": "ANOMALY", "score": 0.92, "detail": "EWMA / CUSUM upward drift alarm triggered at boot 12"},
        "pcrs": {
            "PCR0": "7e3b8a1c9f4d2e0b5a6c7d8e9f0a1b2c3d4e5f6a",
            "PCR1": "c9e4b2d1a0f8e7c6b5a4d3c2b1a0f9e8d7c6b5a4",
            "PCR2": "f8a7b6c5d4e3f2a1b0c9d8e7f6a5b4c3d2e1f0a9",
            "PCR3": "3d2e1f0a9b8c7d6e5f4a3b2c1d0e9f8a7b6c5d4e",
        },
        "verdict": "WARN",
        "reason": "Authentic signatures verified; Multi-Boot EWMA / CUSUM drift monitor detected persistent accumulation",
        "attestation": "REDUCED_TRUST (Multi-Boot Drift Alarm)",
        "attributions": [
            {"feature": "cusum_drift_score", "observed": "5.4 CUSUM", "baseline": "0.0", "sigma": "+5.4sigma"},
            {"feature": "ewma_boot_time", "observed": "101.9 ms", "baseline": "40.5 ms", "sigma": "+4.8sigma"},
            {"feature": "ctx_switches_invol", "observed": "18", "baseline": "2", "sigma": "+3.9sigma"},
        ],
    },
    "benign_load": {
        "title": "Benign Control: Host CPU Load",
        "description": "Authentic boot executed during heavy host background computation; ratio features maintain structural baseline.",
        "stages": [
            {"id": "S0", "name": "BootROM", "status": "OK", "time_ms": 7.5, "detail": "Verified S1 (background host load)"},
            {"id": "S1", "name": "Bootloader", "status": "OK", "time_ms": 15.0, "detail": "Verified S2 (background host load)"},
            {"id": "S2", "name": "Kernel", "status": "OK", "time_ms": 38.0, "detail": "Proportional latency scaling"},
            {"id": "S3", "name": "Init/Services", "status": "OK", "time_ms": 24.0, "detail": "All services completed cleanly"},
        ],
        "gate1_crypto": {"status": "PASS", "algorithm": "ML-DSA-65", "detail": "All signatures valid"},
        "gate2_measure": {"status": "PASS", "detail": "PCR state allowlisted"},
        "gate3_behavior": {"status": "PASS", "score": 0.38, "detail": "Ratio features (stage fractions) invariant to CPU scaling"},
        "pcrs": {
            "PCR0": "7e3b8a1c9f4d2e0b5a6c7d8e9f0a1b2c3d4e5f6a",
            "PCR1": "c9e4b2d1a0f8e7c6b5a4d3c2b1a0f9e8d7c6b5a4",
            "PCR2": "f8a7b6c5d4e3f2a1b0c9d8e7f6a5b4c3d2e1f0a9",
            "PCR3": "3d2e1f0a9b8c7d6e5f4a3b2c1d0e9f8a7b6c5d4e",
        },
        "verdict": "PASS",
        "reason": "All signatures valid; behavioral variance accounted for by invariant stage ratios (NO FALSE HALT)",
        "attestation": "TRUSTED (Valid Boot Under Load)",
        "attributions": [
            {"feature": "t_total_boot", "observed": "84.5 ms", "baseline": "40.5 ms", "sigma": "+2.8sigma"},
            {"feature": "stage_time_ratio_s2", "observed": "0.45", "baseline": "0.42", "sigma": "+0.4sigma"},
            {"feature": "verify_time_fraction", "observed": "0.26", "baseline": "0.28", "sigma": "-0.2sigma"},
        ],
    },
    "a5_cross_sku": {
        "title": "Attack A5: Held-Out Cross-SKU Substitution",
        "description": "Authentic server-profile kernel component booted on edge target; strictly held-out out-of-sample evaluation.",
        "stages": [
            {"id": "S0", "name": "BootROM", "status": "OK", "time_ms": 3.1, "detail": "Verified S1 with ML-DSA-65"},
            {"id": "S1", "name": "Bootloader", "status": "OK", "time_ms": 8.5, "detail": "Verified S2 with OEM root key"},
            {"id": "S2", "name": "Kernel", "status": "WARN", "time_ms": 38.0, "detail": "Foreign NUMA table allocation anomaly"},
            {"id": "S3", "name": "Init/Services", "status": "OK", "time_ms": 15.0, "detail": "Launched services"},
        ],
        "gate1_crypto": {"status": "PASS", "algorithm": "ML-DSA-65", "detail": "Authentic OEM signature valid"},
        "gate2_measure": {"status": "PASS", "detail": "Valid measurement hash"},
        "gate3_behavior": {"status": "ANOMALY", "score": 0.57, "detail": "Generalizes to foreign SKU memory/allocation footprint"},
        "pcrs": {
            "PCR0": "7e3b8a1c9f4d2e0b5a6c7d8e9f0a1b2c3d4e5f6a",
            "PCR1": "c9e4b2d1a0f8e7c6b5a4d3c2b1a0f9e8d7c6b5a4",
            "PCR2": "e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0",
            "PCR3": "3d2e1f0a9b8c7d6e5f4a3b2c1d0e9f8a7b6c5d4e",
        },
        "verdict": "WARN",
        "reason": "Authentic signatures verified; Out-of-Sample Behavioral Anomaly Detected on Foreign SKU Profile",
        "attestation": "REDUCED_TRUST (Cross-SKU Anomaly Warning)",
        "attributions": [
            {"feature": "rss_s2_mb", "observed": "64.0 MB", "baseline": "14.0 MB", "sigma": "+5.2sigma"},
            {"feature": "t_exec_s2", "observed": "38.0 ms", "baseline": "10.0 ms", "sigma": "+4.1sigma"},
            {"feature": "ctx_switches_vol", "observed": "28", "baseline": "8", "sigma": "+2.9sigma"},
        ],
    },
}
